# computer based guessing game in which we have to gues the number generated by computer
# it's a use of a library we called Random , which includes random psuedo numbers

import random 

def guess(x): # X is set as parametre for random digit
    random_number = random.randint(1, x) # random number between 1 to x 
    # use of while loops
    guess = 0
    while guess != random_number: # stop the expression when guessed number is equal to generated number
        guess = int(input(f'Guess a Number between 1 & {x}: '))
        # USE OF if STATEMENT
        if guess < random_number:
            print('Sorry, guess again. Too Low')
        elif guess > random_number:
            print('Sorry, guess again. Too High')
    
    print(f'Yay, Congrats! You have guesses the number correctly {random_number} ')
        
guess(15) # number of trials

# USING THE ABOV CODE IT PRINT OUTS THE NUMBER WE SELECTED RATHER THAN TELLING WHETHER IT IS LOWER OR HIGHER THAN THE GUESS
#SO USED if STATEMENTS
